---
- name: Deploy App
  hosts: all
  become: yes
  vars:
    docker_image: "my-app:latest"

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      systemd:
        name: docker
        state: started

    - name: Build and Run Docker Container
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: build
        build:
          path: /home/ubuntu/docker
          dockerfile: Dockerfile
      notify: Restart Docker

  handlers:
    - name: Restart Docker
      systemd:
        name: docker
        state: restarted