name: DevOps Pipeline
on:
  push:
    branches: 
        - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Step 3: Initialize Terraform
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      # Step 4: Apply Terraform to create AWS infrastructure
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 5: Save the EC2 IP to a file for Ansible
      - name: Save EC2 IP
        working-directory: ./terraform
        run: terraform output -raw ec2_public_ip > ../ansible/inventory.ini

  ansible:
    name: Ansible Configuration
    needs: terraform  
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code (to access Ansible playbook and frontend files)
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Configure SSH key to connect to EC2
      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step 3: Copy frontend files and Docker config to EC2
      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ needs.terraform.outputs.ec2_public_ip }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/,docker/"
          target: "/home/ubuntu/"

      # Step 4: Run Ansible playbook to configure EC2
      - name: Run Ansible Playbook
        working-directory: ./ansible
        run: ansible-playbook -i inventory.ini playbook.yml --user ubuntu